### ISSUE TITLE
merge-csv.py: unable to detect delimiter error

### ISSUE THREAD

**Issue by jeftreece** [jeftreece/dnamatch-tools#14]
**Describe the bug**
merging multiple .csv files, which contain multi-line comments (quoted with double-quote character) not properly detected,
causing a runtime error and no merged file

**To Reproduce**
1. create .csv files with a quoted field that consists of a large number of lines
2. run merge-csv.py on those files
3. observe runtime error:

Traceback (most recent call last):
  File "/home/treece/DNA/dnamatch-tools/./merge-csv.py", line 45, in <module>
    dialect = csv.Sniffer().sniff(''.join(lines[0:10]))
  File "/usr/lib/python3.9/csv.py", line 187, in sniff
    raise Error("Could not determine delimiter")
_csv.Error: Could not determine delimiter

**Expected behavior**
properly formed .csv files should be handled without error

**Sample**
Name, ID, Comment
Jef,57,this is fine
Mr X,82,"this is also fine"
Mr Y,99,"this
may
cause
an
error
but
should
be
handled"

**Desktop (please complete the following information):**
 - Python3.9

**Comment by jeftreece** [comment]
fixed in commit 64617062185e95cd24f8f3d9cdcc3575a1ebaf5f for comments that span multiple lines, though if the number of lines spanned exceeds 100, it will probably still fail.
